version: '3.6'
services:
  sticker-convert:
    # image: sticker-convert # Uncomment for building locally
    # build: # Uncomment for building locally
    #   context: . # Uncomment for building locally
    #   dockerfile: Dockerfile.gui # Uncomment for building locally
    image: laggykiller/sticker-convert:latest-gui # Comment out for building locally
    volumes:
      - ./sticker_input:/app/stickers_input
      - ./sticker_output:/app/stickers_output
    ports:
      - 5800:5800
      - 5900:5900